### ISSUE TITLE
[desktop/windows-only] Advanced Option File Associations - Check button not working properly ($15 bounty)

### ISSUE THREAD

**Issue by muckachina** [frostwire/frostwire#117]
Tested on OS: **Windows 8.1 tablet, Windows 10
FrostWire version 6.2.3(build 178)** 
Screen: **Main Menu > Options > Advanced > File Associations**
Test: **Change file settings associations**
**Ref. S-Trans-28**

**Observations:**

This option is only available on Windows.
To reproduce the issue:

1) Go to FrostWire main menu _Tools > Options > Advanced > File Associations_

2) Un-select the option _".torrent" files_

3) Select Apply > Ok 

4) Open again main menu _Tools > Options > Advanced > File Associations_ and you will see the option  _".torrent" files_ is marked again. This check box control is not working. 

If you want to have this '.torrent files' option always active then the check button should be disabled.

**Comment by X-NicON** [comment]
Details

if there is no Association in the HKEY_CURRENT_USER, then the **installer** registers the Association in HKEY_LOCAL_MACHINE.

FrostWire only works with HKEY_CURRENT_USER

when the Association is removed from FrostWire settings, removes a branch in HKEY_CURRENT_USER, and the system takes the Association of HKEY_LOCAL_MACHINE and it turns out that the Association remains the same.

**Comment by gubatron** [comment]
this is a really weird issue, I've tried it and sometimes it works, sometimes it doesn't (meaning the association panel shows up and doesn't)
