### ISSUE TITLE
[Common] Create a .txt file when seeding a file on FrostWire

### ISSUE THREAD

**Issue by alejandroarturom** [frostwire/frostwire#131]
FrostWire should create a .txt file when you seed a file. That .txt file can contain an info saying something like this: "This torrent was created with FrostWire... Search, Download, Play, Share. Get FrostWire.. www.frostwire.com".

**Comment by alejandroarturom** [comment]
@gubatron

**Comment by gubatron** [comment]
Thoughts:
I'm pretty sure I'll be able to do it only for multi-file torrents. Have to test if it's possible to put the .txt file outside the folder being added to the .torrent, but I doubt it, because the client that downloads it could have a file on the parent folder that's named the same and the torrent client could think it has been downloaded or altered and delete the file that was there. Or in the worst/simplest case, it will simply overwrite existing files on the target machines if that were possible.

So I'm not sure if it's technically possible, unless you alter the original structure of the folder that's about to be shared, and that's kind of nasty I think.

**Comment by gubatron** [comment]
a solution to my moral dilema is an UI one.
The .torrent creation dialog should have a checkbox that says:
[x] Include frostwire.txt

It should also be available on the preferences and it could be an opt-out config flag.
