### ISSUE TITLE
[android] Optimize UI refresh in transfers

### ISSUE THREAD

**Issue by aldenml** [frostwire/frostwire#138]
Currently, there is a `TimerService.subscribe` to refresh the transfer list every 2 seconds, but this mechanism does not take in consideration if the view is actually visible or not. Ideally a general solution tied to the `TimerService` should free any UI component subscription of this problem.

**Comment by aldenml** [comment]
Hi @grzesiekrzaca, may be you want to take a look at this

**Comment by grzesiekrzaca** [comment]
In my opinion, the caller should clear it's subscription to anything it doesn't need (he knows best what he needs). In the case of the fragment, it should be in the `onStopped()` method (no longer visible). The problem here is that the notification that shows the download/upload also is updated in the fragments `onTime()` method (which is not ideal due to SRP). I propose adding normal removal of subscription to the fragment and moving the notification update to separate class. 
Clarification:
Due to weird way the fragments are handled here this approach doesn't work (just doing everything in onStopped/onResumed) so I added a check for visibility inside onTime(). If it doesn't pass then the subscription is cancelled. (Also not ideal but will end in at most one redundant call of the timer (without UI logic)) #140

**Comment by aldenml** [comment]
The corresponding call to `onResume` is `onPause`. The way the PR is coded right now, it's possible you  end up creating adding new subscriptions without removing the old ones.

The idea of having a solution more inside the "Timer" framework is that all this UI components potentially have the same problem of "don't refresh if not necessary". This `TimerService` is just an UI timer running in the main looper for simple UI refresh, why not put the solution here (not necessarily inside the class `TimerService`?

I do agree with the idea of moving out the task of updating the permanent status notification from the transfer fragment.

Ok, I think it's a good idea that we start with the permanent status "cleanup" that should be done in the right place (and in a separated PR).

**Comment by grzesiekrzaca** [comment]
Hmmm add `isSubscriptionStillValid()` to the interface and make the Timer ask the subscribed UI element?

**Comment by aldenml** [comment]
What if instead of (re)subscribing, we just let the `TimerSubscription` decide if effectively call the `onTime`. For that, I would ask if the observer is (or is in) an `Abstract(Activity|Fragment)`. We can add one more state to them if necessary.

**Comment by grzesiekrzaca** [comment]
I think that that makes using it for stuff like updating the notification weird, and adding anything more to be serviced by it requires it to change. This way we just add `observerRef.get().isSubscriptionStillValid()` next to `!isUnsubscribed()` in `TimerSubscription` and let whatever we want to update on time worry about itself.

**Comment by aldenml** [comment]
Do yo feel like coding the idea for testing? I rather start with the permanent status cleanup, btw.

**Comment by grzesiekrzaca** [comment]
Yes. By permanent status cleanup you mean splitting this PR into two? One with changes to the timer and the other with `NotificationUpdateDemon`? (I'm not sure I follow).

**Comment by aldenml** [comment]
Yes, let's first review a PR with the new `NotificationUpdateDemon` alone, it should be easy to make a couple of observations there.

**Comment by grzesiekrzaca** [comment]
#141 `NotificationUpdateDemon` standalone

**Comment by gubatron** [comment]
can this be closed or there's still work to be done with the subscription logic like we talked @aldenml ?

**Comment by aldenml** [comment]
Still work in progress.

**Comment by gubatron** [comment]
>Hmmm add isSubscriptionStillValid() to the interface and make the Timer ask the subscribed UI element?

I think the idea is close but semantically incorrect. I think the word "valid" is a bit too strong, because a developer implementing it in the future might think that once a subscription is invalid it's no longer good, however, if you had a method that hinted that on this next update we can "skip" doing anything for that subscriber, it might be a bit clearer.

I'd add a "boolean skipMe()" method on the subscriber interface.

This way if the subscriber happens to be a view on an invisible state (in this particular case), the subscription service can keep going on to the next subscriber when that method returns true.

**Comment by grzesiekrzaca** [comment]
went with canBeSkipped(); #151

**Comment by aldenml** [comment]
I will be a little more explicit. I rather ignore `NotificationUpdateDemon` until this is done, I just want to mention that `updatePermanentStatusNotification` seems to me that put a lot of pressure in the UI, since it creates the views in every tick, I don't think that's necessary.

My idea about `TimeService` is that it's a primitive mechanism to allow for low frequency tick based UI views refresh. Ideally, it should blend in our view framework (`AbstractActivity`, `AbstractFragment`, `AbstractDialog` and `AbstractFragment`) like something more inline with the UI message loop, and eventually avoid the direct `subscribe/unsubscribe` when possible (more magical). Having said that, I grant that `canBeSkipped` seems that it allows for more flexibility, but that's not necessary the case, that was already possible. We don't have a `canSkipClicksEvents` or similar methods in any UI framework (that I know).  The framework should optimize based on his knowledge of the system's state, and the implementers can optimize if they think it's necessary.

What if you put the following `if` in the `TimerSubscription#onTime`:
```
if (obj is SomethingCanBeVisible && !((SomethingCanBeVisible)obj).isVisible()) skip onTime;
// change SomethingCanBeVisible with Fragment
```

How it compares to the #151 solution?

**Comment by gubatron** [comment]
did you end up finishing this @aldenml, please close if we're done.

**Comment by aldenml** [comment]
not yet, working on it
