### ISSUE TITLE
64-bit

### ISSUE THREAD

**Issue by svnpenn** [frostwire/frostwire#199]
Please add 64-bit version, thank you.

**Comment by gubatron** [comment]
you mean, a windows 64-bit version?

why exactly do you need a 64-bit version for windows? I'm truly curious

**Comment by svnpenn** [comment]
I do not see it specified anywhere, so I am assuming the Windows version is 32-bit. Most software I use now is available in 64-bit:

- Windows
- 7-Zip
- Avidemux
- Firefox
- MPC-HC
- Notepad2
- VirtualBox

I prefer to use a 64-bit torrent client. I am currently using qBittorrent, but the 64-bit version is not official.

**Comment by gubatron** [comment]
but do you know why?  :)
what would you be able to do with a 64-bit client, I'd like to know the use case you have in mind that demands 64-bits. We can do it, we just don't know if it's even worth going to the trouble of double binary distribution as we haven't seen files large enough to require using 64-bit addressing yet.

In the case of Mac Apple forced everyone to switch to 64bit, but the Windows ecosystem still has hundreds of millions of devices running on 32-bits only.

**Comment by svnpenn** [comment]
The question is not "why should we have a 64-bit version" but "why should we have a 32-bit version". I believe XP was the last system using 32-bit as the default, and XP is no longer supported. If Vista default is 32-bit, then it would be worth having both versions.

**Comment by gubatron** [comment]
I think you're biased because you have a 64-bit CPU but there's still a great deal of people on 32-bit cpus, most of them running windows. The question seems right when you look at the numbers, and specially when you can't cite a use case of why do you need it.

32-bit software is perfectly compatible in windows, and we're still not even able to store files that are exabyte long on a single disk, when we have multi exabyte disks available and exabyte files, that's the one use case that justifies the upgrade. In the meantime, it'd be overkill to recompile all the binary components and set up dual distribution mechanisms (or an installer that's double the size and includes binaries for both architectures)

These are numbers from 2010, from Microsoft
![main-qimg-8966caae40d4fbf4c9b78080eff529c6](https://cloud.githubusercontent.com/assets/163977/19397814/a9bfb1a0-9206-11e6-8a53-64135048ed99.png)

If you find more recent numbers from Microsoft that show that there's about of 10% windows users running on 32-bit cpus in 2015-2016, then we'll do all the work, otherwise, it's just unnecessary headaches, and decisions will need to be made on how to go about it, for instance we'd have to distribute 2 different JREs with our installers and rebuild every .dll to 64bit, and revamp our upgrade servers and the client's logic to only download an installer of its own architecture.

For now, we see no real reason to make the switch.

**Comment by svnpenn** [comment]
@gubatron posting data from 2010 is laughable. If you want to make your case with ridiculously old data, then I see no point in pursuing this issue further. I will continue to use PicoTorrent or qBittorrent, maybe on day you will take your head out of the sand. Good day

**Comment by svnpenn** [comment]
https://github.com/hadouken/hadouken/issues/228

**Comment by svnpenn** [comment]
https://github.com/irzyxa/Volume2/issues/3

**Comment by svnpenn** [comment]
https://github.com/malensek/3RVX/issues/73

**Comment by svnpenn** [comment]
https://github.com/visualfc/liteide/issues/883

**Comment by gubatron** [comment]
I see this old issue being referenced in a bunch of different projects, it'd be great to find out what the current distribution of CPUs is, perhaps 2018 will be a good year to put some effort into an 64-bit distribution.
