### ISSUE TITLE
[desktop] Downloads pausing and stopping on MacOSX Sierra (build 207)

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#219]
Users have reported downloads pausing and stopping on MacOSX.

I downloaded the installer once again from the site and I could confirm the issues.
Even the Jyant promo has issues downloading with over 40 seeds available.

I've turned off my firewall, and the issues continue, there must be something off with libtorrent, or sierra and JRE.
![screen shot 2016-10-23 at 6 29 39 pm](https://cloud.githubusercontent.com/assets/163977/19630783/aed5060a-994e-11e6-84d3-f89294d76c0e.png)

**Comment by aldenml** [comment]
This is not good.

**Comment by muckachina** [comment]
The status of these files are not 'paused', they say 'downloading' and users (specially from Windows) report this a lot of time... how can you can check if is libtorrent or the connection itself with the torrent file? because when I report these things you since I can download other torrents then 'is not FW is the file'...

**Comment by aldenml** [comment]
Test now with https://github.com/frostwire/frostwire/commit/8ba5ea2d2354514e97b4f8b5cbc249bab2df0e69
