### ISSUE TITLE
[android] My Files > My Ringtones empty context menu when multiple files are selected

### ISSUE THREAD

**Issue by grzesiekrzaca** [frostwire/frostwire#226]
Android 6.0.1 Samsung S5

1) Navigate to my ringtones
2) Check 2 ringtone files 
3) Hold to open context menu 
Is:
Empty menu
Expected:
Populated context menu
 
Alternative repro:
1) Navigate to my ringtones
2) Check 1 ringtone file
3) Navigate to my music
4) Check  at least one file
5) Navigate to my ringtones 
6) Hold to open context menu 
Is:
Empty menu
Expected:
Populated context menu

**Comment by gubatron** [comment]
Good find, this is happening because of changes in android that don't allow us anymore to delete ringtones across all devices.

Plan of action:

1. Hide the checkboxes capability when the user has selected the ringtone media type.
2. When a ringtone is touched (on the right hand side), or long pressed, show an action menu that contains the following actions: "Open", "Use as ringtone"
