### ISSUE TITLE
[android] My Files > My Pictures + My Videos should have the option to be displayed as a [3 to N by M] grid

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#228]
@marcelinkaaa do we have any existing mockups/discussions on this subject?

**Comment by gubatron** [comment]
Note: when I say 3 to N, I'm thinking that in most android phones, on vertical mode we should display a minimum of 3 columns, however, there might be devices with bigger screens, like those phablet ones, perhaps could show 4.

Then when we're in horizontal mode, that number should be larger, perhaps up to 5 or 6 columns. I think we should find a formula so that we keep a ratio that makes it look beautiful while using the resolution at our disposal for more.

**Comment by gubatron** [comment]
I'm thinking once we have the look of this defined, @grzesiekrzaca should take over implementing the list/grid adapter changes

**Comment by marcelinkaaa** [comment]
ok will take a look at old mockups and refresh. In any case grids are pretty standard. Will get back to you soon.

**Comment by marcelinkaaa** [comment]
So the reason I wanted to do grids later with the support libraries in place is that we could modernize the action bar together (with how we display options for a given selected file and a different way to implement 'filter' - which would provide us with more space for content on smaller screens).

So images 8, 9, 10, and 12 show more or less what I imagined with material design libraries in place. 

If we want to implement the grid while leaving the current positions of elements, including filtering, action bar - take a look at 0, 1, 2, 3, 4, 6, 7 (with 3 and 7 showing 2 different possibilities of showing the options). To gain some vertical space for content we could hide the filter bar and the change icon bar on scroll down - shown in pic 5 - and show them again on scroll up. This will help us especially when phone is in horizontal view - pic 11.

Now if you decide it would be best to leave the user with possibility of switching between grid and list view than an icon like on pic 8, can be applied to pic 0. If we would do so I would rather move the title on action bar to the left instead of having it centered.

Lets open for discussion. 

[grid.zip](https://github.com/frostwire/frostwire/files/567977/grid.zip)
<img width="1622" alt="grid" src="https://cloud.githubusercontent.com/assets/2339972/19951796/cd8299a6-a136-11e6-91a0-b0f02dcfadb3.png">

**Comment by gubatron** [comment]
Decisions:

***Let's not have an option to go back to the list-like view***, let's just give them a grid, however, by doing this, there's no way to know the name of an image, so we should have one new action to display image information, it could be as simple as showing an informational popup that tells us as much information as we can have about the touched picture: it's filename, file size, and if we have EXIM data available we could put in there things like shutter speed, aperture, f-stop, perhaps even the Lat/Long coordinates with a link that opens the coordinate in the default Map apps.

**Comment by gubatron** [comment]
As for the checkbox UI, let's go with this one
![screen shot 2016-11-25 at 2 52 07 pm](https://cloud.githubusercontent.com/assets/163977/20635752/c801b7ce-b31e-11e6-8776-e5adb4e465e9.png)

It should be enabled by long pressing on any image, after that long press happens, that image will be the first one selected.

**Comment by marcelinkaaa** [comment]
@grzesiekrzaca  well, how I pictured it is taking the filtering out all-together, not just hiding it on scroll. We can instead have a search icon in the action bar - take a look at the mockups that were added few comments up and let me know what you think. 
What we can hide on scroll is the file-type selection bar to give a user more vertical space for viewing the content.

**Comment by marcelinkaaa** [comment]
@gubatron and @grzesiekrzaca as to the 'informational popup': I do understand that users might want to see the name of the file and with keeping only grid view (no list) we should include it somehow. What I would not want to do is to have a long press used for selection of an image and then a simple press to open a popup. I think people are accustomed to tapping to open something and it would be better - if we already placing a grid to be more visual - to open the image full screen rather than teasing the user with slightly larger image on the grid and then making them go to options and select open with and then go outside of FW to view that image. 

Plus if we have ability to view full screen image - we can add all the info there in two ways:
![1](https://cloud.githubusercontent.com/assets/2339972/20650557/85fd8894-b49f-11e6-9fb7-dfa6c66372c4.png)
Here the info would close on tapping on the picture once and reappear on another tap. We could also add trash icon up top for quick action access. 
![2-2](https://cloud.githubusercontent.com/assets/2339972/20650567/b89198f4-b49f-11e6-8ff8-eece5ae5ca23.png)
Or have something like this - with similar icon somewhere on the screen as the 'i' information icon - that when pressed will open all the info including the file name and size. 

Any thoughts? For, against?

**Comment by grzesiekrzaca** [comment]
I think that might be better. 
Right now it's: 
click - open menu with details option added
longclick - check/uncheck 
you can see how it works on my branch:
https://github.com/grzesiekrzaca/frostwire/tree/feature/gridview_for_files
commit 38-5a
(it's a work in progress, so looking at code is pointless atm [especially FileGridAdapter is in need of cleanup, and no logic to change the number of columns])

**Comment by gubatron** [comment]
love it @marcelinkaaa

**Comment by gubatron** [comment]
@grzesiekrzaca please start a pull request for that branch so we can see the entire diff without having to check every commit one by one.

Please title it something like "[android/WIP] Grid view for My Files".
Once you think it's ready for a revision to merge, remove the "/WIP" from the title.

**Comment by gubatron** [comment]
@grzesiekrzaca  Just had a meeting about this branch with @marcelinkaaa and we were able to make some decisions to keep the experience consistent when interacting with list items vs grid items.

1. Single touches on any item (be it grid or list) should open|play the touched file.
2. Long presses on any item should bring out the selection mode. (idea: long pressing on any item while on selection mode, dismisses selection mode)
3. When selection mode is available, there will be a **fixed** (fixe = it will stay there even if you scroll on the list or grid) horizontal checkbox that reads "[ ] Select all"
4. Once one or more files are selected, the menu icon will appear on top
5. On list view items, we will have the menu icon on the right in case the user wants to bring out any of the options available for single file selection
6. Seeded files should have a discreet "seeding" icon so the user is aware of what's being shared when browsing.
7. We will have to implement a simple image viewer like the one shown in above screenshots.

@marcelinkaaa will make adjustments to her mockups, once she sends them I'll put the final screenshots here.

**Comment by marcelinkaaa** [comment]
It's late and I am off tomorrow, but I will finish right after coming back.
The layout and set up should stay the same - the thing I need to work on it some visuals and icons such as the discussed 'selection' icon in the action bar, the inconsistent checkboxes in selection mode in my images, how image information are shown in single full screen image view, etc. 

For now attaching screenshots as pngs and a link for a slightly more interactive mockup. You can open the link and save it on your phone - so it feels more like an app. 
https://xd.adobe.com/view/2accfaf0-9b5b-4b50-932d-7f806bcf8aae/

[my_files_draft.zip](https://github.com/frostwire/frostwire/files/617973/my_files_draft.zip)

**Comment by grzesiekrzaca** [comment]
I'm working on the selection mode for the fragment (as to break the whole task into smaller parts for CR as pre @aldenml request) and have a question: 
Don't we want an interactive label for selecting all/deselecting all (ie. if the checkbox is checked it would read deselect all if it is not checked it would read select all)

**Comment by votaguz** [comment]
Hi @marcelinkaaa, after review the zip file with all the interfaces i have a question, related to the spacing for images and other elements inside containers, where i can get those values ? 
Should i just follow the material design guidelines or there is another source to get that? 

Thanks.

**Comment by marcelinkaaa** [comment]
Hi there @votaguz ... awesome, are you giving it a go? Yes go with material design guidelines! After you are done or even during I can go in and make any design adjustments (fonts, colors, spacing). There was just a few minor updates to the designs on My Files so I will send those over to you as well.

**Comment by marcelinkaaa** [comment]
Hi @votaguz - so again material guidelines are enough. I might change the look of the checkboxes later on - but that is just styling which I can take over later. Together with gubatron, we need to work first on how to access the context menu of item while in grid and in selection mode. This will most likely involve redoing the toolbar while on selection mode. Not sure if you would like to wait until that change is done. As soon as we have something I will let you know.

**Comment by votaguz** [comment]
Sounds good, thanks!

**Comment by votaguz** [comment]
Hi guys, seems like build process is broken, i'm getting this error when i try to run the project. 
![screen shot 2017-04-03 at 11 55 33 pm](https://cloud.githubusercontent.com/assets/368680/24641909/06c6863c-18c9-11e7-8b43-ea4461a277f7.png)

**Comment by gubatron** [comment]
Try:
1. Gradle sync
![screen shot 2017-04-03 at 11 10 32 pm](https://cloud.githubusercontent.com/assets/163977/24642196/c2fd43f6-18c2-11e7-8d18-6b328258a9b4.png)

2. Making sure you've updated all your android toolset (SDK Manager), we've done updates on our gradle to the latest toolset
![screen shot 2017-04-03 at 11 11 01 pm](https://cloud.githubusercontent.com/assets/163977/24642203/d7c217b2-18c2-11e7-8e86-6030887a1b82.png)

3. Clean and rebuild
![screen shot 2017-04-03 at 11 11 41 pm](https://cloud.githubusercontent.com/assets/163977/24642217/ed24a0d4-18c2-11e7-8cf8-c720439a9ced.png)

**Comment by gubatron** [comment]
Also, please rebase with master, we made a lot of changes since last week to make sure this branch you're working on will work a lot better in terms of user experience.

**Comment by marcelinkaaa** [comment]
@votaguz I have no problems running the app here. 
Also I think you should feel free to start working on the grid. The new selection mode (toolbar) is already set up (with few minor bugs that shall be fixed).

**Comment by votaguz** [comment]
Hi, at the end i just downloaded a fresh copy from the repo, seems like something wasn't right in my local copy. I'm already adding my changes again. Thank you.
