### ISSUE TITLE
[android] Eastern European translations missing.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#265]
Let's take care of the rest of Easter Europe users now, in this order:

1. ~Ukraine~ (`uk_UA` - 44.6m people)
2. ~Romania~ (`ro_RO` - 19.3m people + 4m people from Moldova)
3. ~Hungary~ (`hu_HU`  - 9.8m people)
4. ~Belarus~ (`be_BY ` - 9.4m people)
5. ~Bulgaria~ (`bg_BG ` - 7m people)
6. ~Slovakia~ (`sk_SK ` - 5.4m people)

and let's also throw Thai in the mix
7. ~Thailand~ (`th_TH ` - 67m people)

**Comment by gubatron** [comment]
@muckachina perhaps you still have the contact of the guy that did Ukranian for desktop, it'd be awesome if you could help us get it translated to Ukranian

**Comment by gubatron** [comment]
@alejandroarturom I'm re-assigning this to you.

**Comment by muckachina** [comment]
I cannot find the guy you recommended me back in 2012 (Micha P. username in elance was witty2011) because eLance is now upWork...

The most similar guy from Ukraine is Michael Kolesnikov:
https://www.upwork.com/o/profiles/users/_~01c940da40551c5724/

He works for customer support so perhaps inviting him when posting the job could be a good idea @alejandroarturom  to see If he wants to participate.

**Comment by gubatron** [comment]
well if we can't find him, just do it as best as you can @alejandroarturom
