### ISSUE TITLE
Material design makeover of the whole app

### ISSUE THREAD

**Issue by vipulasri** [frostwire/frostwire#280]
I would love to work on revamping the whole app as per material design spec and guidelines.

**Comment by gubatron** [comment]
@vipulasri most excellent news, your help will be most welcome.

Please talk to @marcelinkaaa  and @grzesiekrzaca they've already started a branch related to this (They've started with the `Settings` screen which wouldn't be the least disruptive)

This will a be an interesting refactoring/rearchitecturing challenge, as our activities inherit from an `AbstractActivity` class, the same for our `ListAdapters`, since we started this app when Android was still very immature and we had to fill a lot of gaps that existed at the time.

Ideally many of the new things brought by material design apis have the gaps filled for us and we'll be able to get rid of our custom abstractions and do things more with the norm, we just have to be very careful and keep those parts of our code that took years to mature and not lose that.

[Please see this ticket](https://github.com/frostwire/frostwire/issues/242)

PS: how did you come across our code, do you maintain a fork?

**Comment by vipulasri** [comment]
@gubatron I have forked the source code and going through it. I think it requires a major refactoring, so I would like to know from where should I start so that my work doesn't conflict with the person working on same.

**Comment by marcelinkaaa** [comment]
@vipulasri Hi there, we are currently working on Settings Activity, with few other like Buy Activity and About Activity being done. Not sure what would be next. @gubatron @aldenml any ideas as to what we should focus on next?

**Comment by vipulasri** [comment]
@marcelinkaaa @gubatron @aldenml I would like to start from refactoring the main screen.

**Comment by gubatron** [comment]
@vipulasri if we take a very granular approach as to what needs to be refactored then I think we can make it happen.

Before you send any pull requests, let's try to go over what you have in mind, preferably in an itemized fashion.

Then for each specific change you make we'd love for you to create a feature branch and to commit things as granularly as possible on that branch, this way it will be a lot easier to review, discuss and merge, even on a cherry-pick fashion.

These big refactors are in our plans, we want and need the help, but we'll be very strict with them as again, you're talking about a neuralgic portion of the user interface and a lot interacts with MainActivity.
