### ISSUE TITLE
[android] Excessive Data Consumption

### ISSUE THREAD

**Issue by kad3mlia** [frostwire/frostwire#45]
When FrostWire is running, it consumes too much data, even with no active Transfers (downloading or seeding).

Tested in 1hr, consumed 2MB. Users report Gigabytes of data over longer periods of time.

FIX: When not actively downloading or seeding, there should be no additional data consumption, even for connecting to the network. Having have to turn BitTorrent or DHT off during idle time should not be a solution to this issue.

Even though technically not a bug, in from technical standpoint, it's important enough to the users I have marked as such and should be treated as such.

**Comment by gubatron** [comment]
As of now, these peers are contributing traffic to route queries on the DHT so overall they're helping, but I understand the issue, specially with limited data plans.

Tomorrow I'm meeting with @aldenml , let's see if we haven't done this because it's not easy to stop/start the session automatically. This would mean adding a new state to our logic, I'd call it "Suspended".

In reality it stops the bittorrent engine, but how do you know that you've stopped it manually or you stopped it because you switched out of Wifi into 3G.

It seems that this would be happening only because the user has the setting to use Bittorrent in 3G on.

However I see your point, if you have no transfers going on, turn off Bittorrent until you have active transfers.

It could be expressed in the UI as a new "Data saver mode", we should explain that if you have lots of data you should contribute bandwidth to the network for DHT routing purposes, sort of a netiquette thing.

Also, it would be easier to make it a unlockable feature.

**Comment by gubatron** [comment]
Other things to consider:

- How much data is Flurry consuming?
- How much data is AppLovin consuming?

It might be good to perform a test in which you disable BitTorrent completely and see how much data was used by the app for like 2 hours by these libraries.

**Comment by kad3mlia** [comment]
Transfers Empty.

Tested with wi-fi off, data on, at home with BitTorrent On, DHT on and BitTorrent enabled on 3G/4G, not seeding:
8:59 - FW 40.64MB 
10:55 - FW 40.81MB

Tested with wi-fi on, but outside with no known networks, data on, BitTorrent off, DHT off, and bit torrent disabled on 3G/4G

8:34 - FW 40.05MB
40:45 - FW 42.89MB

I will do a few more tests with just BitTorrent off, with just DHT off and just 3G/4G disabled. 

I have a feeling it's either the video ads or our don't use on mobile data settings are not working right.

**Comment by aldenml** [comment]
I reviewed this issue and looked for potential sources.

- It's hard to tell how the users see how much data FW consumes, if they go to the reporting tool from Android, that data is cumulative over many days. We need to instrument a better way to get this data from users.

- I couldn't see any significant traffic in the DHT (that is variable) but if the phone is not using Wi-Fi, the DHT has no way to receive or send packets, it simply doesn't works in 3G/4G.

- AppLoving cache videos and images in the folder Android/data/com.frostwire.android/files/al, and at least the videos are between 2MB and 3MB. No idea if we are re-triggering new assets that need to be cache or if they could add to a significant size over a short period of time, or if there is a way to disable this in 3G/4G.

I suggest perform a more granular test to determine if this is in our side or a third party component.

**Comment by gubatron** [comment]
mitigated with Remove-Ads.

**Comment by gubatron** [comment]
mitigated with Remove-Ads.
