### ISSUE TITLE
[android/critical] "Seeding" setting not working properly.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#469]
Steps to reproduce.

1. Turn of seeding on settings.
2. Start a full torrent download. It should go to "finished"
3. Start a partial torrent download.
4. While the download is in "Downloading" state, use the action bar "Pause all" menu action
5. Try the action bar "Resume all torrent transfers"

the previous "Finished" transfer will go into "Seeding"

(starting point `TransferManager.instance().resumeResumableTransfers();`)

**Comment by aldenml** [comment]
looking at it

**Comment by gubatron** [comment]
Thanks!

**Comment by aldenml** [comment]
This should fix it: https://github.com/frostwire/frostwire/commit/d2ad5c7f9627f09cc39e4d8325fe4ba434df4f22

@muckachina is there a test case that covers this?

**Comment by marcelinkaaa** [comment]
Works well on my phones, thank you.

**Comment by muckachina** [comment]
@aldenml @gubatron The tests here are:

> Clear all the finished transfers

> "Pause/Stop" all transfers (Only when there are files 'Downloading'

> Resume all torrent transfer

There are more issues related to this menu, I'll be testing carefully today since I was with desktop this week.

Here another issue related to this bug commented with @marcelinkaaa yesterday night:

The menu option appears and disappear in an inconsistent way (here an example with 'Resume all torrents':

_The option ‘Resume all files’ appear when you start to download a new file but everything on Transfer is ‘Downloading’ so this option shouldn’t appear (The ‘Pause’ option disappear from menu when all files are ‘paused’)_
![screen shot 2017-06-08 at 9 57 48 am](https://user-images.githubusercontent.com/1534723/26932322-2d860734-4c31-11e7-9f05-b7adb4c169eb.png)

After few downloads are complete the ‘Resume’ option disappears… 
![screen shot 2017-06-08 at 9 57 58 am](https://user-images.githubusercontent.com/1534723/26932359-449d116a-4c31-11e7-9e1f-92d36f39fa1f.png)

I'll test the current scenarios to open this as a different issue since this code has been modified lately and there are about 4 releases within the last 4 days, I'll be focused on what is on the website right now 1.9.6-build-391

**Comment by aldenml** [comment]
Ok, I'm reopening for review

**Comment by muckachina** [comment]
Question about the 'Seeding' issue opened here because I think it was an initial logic discussed already @gubatron and not a bug:

the action bar "Resume all torrent transfers" > Means ALL torrents will start 'Downloading' or Seeding because 'Finished' torrents shouldn't pause, they remain Seeding

So, "the previous "Finished" transfer will go into "Seeding"" shouldn't be a bug

Please let me know If you changed the logic and it will remain in that way. Now I cannot see an option to 'Pause' Downloading files and the last that is 'Finished' cannot be Resume when I click 'Resume all torrent transfer'

**Comment by aldenml** [comment]
I think everything is the same, the bug was that _Seeding_ was off in the settings. Is it something wrong UX wise?

**Comment by muckachina** [comment]
@aldenml These are the scenarios:

![screen shot 2017-06-08 at 12 52 52 pm](https://user-images.githubusercontent.com/1534723/26940675-94dae0cc-4c49-11e7-921b-13118913c7ab.png)

So, regarding the initial issue 'Seeding Off' but one file started Seeding the initial solution is not complete:

'Resume All Torrents in Transfer:

Active when there are Torrent files 'Paused' and/or Finished > The files 'Paused' will start 'Downloading' and 'Finished' torrents will start 'Seeding' If Seeding is ON > **This is OK**

 If Seeding is OFF then **a notification to Resume the file is needed and 'Seeding' should be turned On or remain Off > KO**

**Comment by aldenml** [comment]
OK, notification missing, that should be "easy"

**Comment by muckachina** [comment]
Updating issue for FrostWire 1.9.6-build-393 after @marcelinkaaa getting 'Seeding' files with 'Seeding' option Off on Settings:

This is an scenario where the issue still happens:

1) Go to FrostWire Settings > Torrent Preferences and make sure 'Seeding' options are OFF

2) Go to Search screen and start downloading a torrent file (it could be a promo or different file)

3) Once the file appears 'Finished' on Transfer go to 'Search' screen and download the same torrent file again

4) **You will see how the file changes from 'Finished' to 'Seeding' although the 'Seeding' options remain OFF**

This is the only scenario I can reproduce right now on these devices, however, Natalie has a video where is happening even downloading some promos just once... still trying to confirm that case and any others that can trigger 'Seeding' on Transfer when the Settings are Off.

**Comment by gubatron** [comment]
hmm, it tries to resume it. Might be a feature, not a bug, Desktop is doing the same thing.
As this is the same as grabbing a "Finished" (aka paused) transfer and resuming it.

But I think you're right, this is not the correct behavior, this is a bug we've probably had for many years.

**Comment by aldenml** [comment]
@muckachina I expect the menu to behave with more consistency now, and the issue in the last comment is fixed (both android and desktop) with https://github.com/frostwire/frostwire/commit/3597d39ddb386ae94b360699a0bcf33c9a0b643c

**Comment by gubatron** [comment]
can this be closed now @muckachina ?

**Comment by muckachina** [comment]
Yes @gubatron the scenarios on Menu has been fixed, tested from git and related to these two issues:

https://github.com/frostwire/qa-android/issues/128

https://github.com/frostwire/qa-android/issues/127#issuecomment-308863973
