### ISSUE TITLE
[android-ux] More convenient access to "Search" from Transfer screen.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#58]
@alejandroarturom made a good suggestion for the transfer screen, as it is, it takes two clicks to get back to "Search" from transfers. This is def. one of the most common actions from this screen (until your downloads are finished)

There should be some UI shortcut to get back, I'd like to know what you think @marcelinkaaa

**Comment by marcelinkaaa** [comment]
The floating action buttons that are used for the most common action in your app and reused throughout different pages for easy access are a nice solution but only used in material apps. 
And since we are using the search field - adding another icon to the action bar might be taken more as a filter than return for the search screen. 
For now I don't see a clean way to introduce it, so if anyone has some ideas lets brainstorm.

I will look into it, however would rather see the stats as to how people navigate from the transfer screen. I always tap androids back button which the phone already has and people are accustomed to using. I bet most people go to transfers after search so back will take you just there. Would rather keep it clean as it is for now as we already have a navigation for that. Will look for ideas though.

**Comment by gubatron** [comment]
"search field"? there's no search field on transfers.

**Comment by marcelinkaaa** [comment]
@gubatron  I know. I was referring to the search field on the search activity, just trying to convey that using any search icon in the action bar of a transfer screen might be taken more as filtering that particular screen and not a shortcut to the search screen.

**Comment by gubatron** [comment]
oh got it. Yes. Then, if we had a very specific looking icon for the Internet/Torrent search we could do away with the possible confusion so the user doesn't think they're going to look within their own transfers.

**Comment by gubatron** [comment]
@marcelinkaaa let's revisit this enhancement, let's make going back to search more natural from this screen

**Comment by marcelinkaaa** [comment]
My opinion: it would most likely be best to leave it as it. Sorry for the long message!
**Reasons:** 
- majority of the users that will come to the transfer screen will come after a particular download is started, in this case android already has a ‘build in’ way to go back to the previous screen - back button, which would be the most natural.
- introducing another icon in the action bar (especially on smaller screens) would not be optimal due to limited space. Android recommendation is up to 3 icons - that includes the three dots (menu overflow), we already have FW logo on the left and text in the center not left. Unless we incorporate search with adding magnets and torrents - the + icon, one of the icons will be hidden under overflow menu anyways on the smaller screen devices
- across the android apps the action bar icons and options are commonly used for the screen they are on. Using a search icon there would be most likely taken as a way to filter the transfer list - just like we do in My Music section. Of course we can introduce new icon but the learning curve will be higher here if its something different, and in the complex app like ours I would suggest sticking more to what users would understand at ‘first sight’. 

**Things we could do:** 
- Floating buttons: “Not every screen needs a floating action button. A floating action button represents the primary action in an application.” A floating button is not used in all the new apps but its used to the point that many users should understand its use. In most cases its self explanatory. We could also reuse it other places other than transfers. However, since we have no support libraries in the app we would have to code it ourselves. **IMG_1** https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button
- New icon: still could not think of something that would not suggest searching the page (filtering) and is used for getting back to search screen. If we introduce a completely new icon for search screen I would than change it also on the navigation menu so users remember it a lot better - maybe treat it more as ‘home page’. In any case **IMG 2** shows what changes I would want to see in the action bar across the app to get needed space for that extra icon. 
- We could potentially combine the add ‘+’ action in transfers with search. If a user would input a search term they would go back to search screen with those results, if torrent or magnet the download would simply start in transfers. It makes search faster but it is not addressing return to search for current search results. A user would need to still use the back button. **IMG_3** 
- We could make the '+' button take a user straight to the search page and make sure that in that search field you could also add magnets and copy and paste torrents. But than if you later want to use the same search field to add filters - I think everything could be much too messy. 

![img_1](https://cloud.githubusercontent.com/assets/2339972/18396328/1140af8c-7691-11e6-83b1-ba731076ad59.png)
![img_2](https://cloud.githubusercontent.com/assets/2339972/18396327/11409704-7691-11e6-8d5d-d52ffec08fdb.png)
![img_3](https://cloud.githubusercontent.com/assets/2339972/18396326/113e206e-7691-11e6-933c-fb169c3ded4d.png)

**Comment by gubatron** [comment]
thank you for thinking this deeply, i also want you to consider (overall your future UX plans) that maybe within a year we will have to provide a great experience for people on Chromebooks.

this holiday season I bet every new chromebook hardware maker will be compatible with android apps.

**Comment by marcelinkaaa** [comment]
Yes! Ive been reading more about it and will slowly prepare move visual materials and mockups. I also have another working prototype for FrostWire in the future which makes shows better UI for  settings, torrent details, different types of filtering, and some new nicer UI elements across the device.

**Comment by gubatron** [comment]
At some point soon in the future (now that we have material design) we will implement that floating UI navigator as the way to easily move back and forth in random directions.
