### ISSUE TITLE
[android] Empty files when you do a search

### ISSUE THREAD

**Issue by alejandroarturom** [frostwire/frostwire#63]
There are some reviews on Google Play  about people complaining that they found sometimes empty files when they download a song.

I think maybe we can filter these results. If the file size < 100kb, it doesn't appear in the results.

**Comment by gubatron** [comment]
The only reasons I can think of are:

- There was a connection error during the download and somehow FrostWire didn't notice and added ("media scanned") the file to the library.
- The file is ok, but it's in a format not compatible with the android audio player.

You can't really filter files by size like that, the user may have purposefully have downloaded a file with a short sound FX.

**Comment by kad3mlia** [comment]
I think it's probably a non-issue. People routinely do not know what they are talking about and you really have to digg deeper to translate it to a real issue. 

They will call software website, torrent package an album, they complain there is no audio because they are in a different category - empty downloads could mean Error, file said it was downloaded but failed and size is 0kb (old issue) etc. I haven't seen any complaints of that sort on support nor google play..
