### ISSUE TITLE
[android] Android P refactor: BitmapFactory -> ImageDecoder

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#675]
Android P deprecates `BitmapFactory`.

This affects 
 - `com.frostwire.android.util.ImageCache`
 - `com.frostwire.android.util.ImageLoader`
 - `com.frostwire.android.gui.adapters.menu.SetAsWallpaperMenuAction`
 - `com.andrew.apollo.cache.ImageFetcher`

**Comment by aldenml** [comment]
well, the title is a little misleading, I guess in part because the blog post was a little loose on it. The situation is that when using Android P, `ImageDecoder` is a better and improved alternative to `BitmapFactory` and so far, no actual API deprecation have been done. In any case, even if we target Android P, our minimal API will be lower for a long long time.

https://android-developers.googleblog.com/2018/03/previewing-android-p.html

**Comment by gubatron** [comment]
well, they say "ImageDecoder deprecates BitmapFactory", I say we refactor when we're doing target upgrade around July/August

**Comment by aldenml** [comment]
we can't, even if we target that API, we still support lower ones
