### ISSUE TITLE
[all] OkHttpClient revision. Also checking okHttp's shutdown

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#824]
Want to check if we do something like this on Android's exit, as well as Desktop's shutdown.

```java
            okHttpClient.dispatcher().executorService().shutdown();
            okHttpClient.connectionPool().evictAll();
            try {
                okHttpClient.cache().close();
            } catch (IOException e) {
                e.printStackTrace();
            }
```

**Comment by gubatron** [comment]
Other interesting findings. YT's extractor uses its own custom `Browser` object during search.

This browser's `disconnect()` method doesn't seem to be invoked.
`Browser` uses a `HTTPConnectionImpl` to do its networking. It's implemented using a regular `java.net.Socket`, which I only see being closed whenever there's an `IOException` or in the event of a redirect. Never when we're done we close these sockets.

This might be a big performance issue causing network errors and out of memory errors.

**Comment by aldenml** [comment]
Regarding your comments/questions:

1. I take care of the connection pool eviction in android in `EngineService#stopOkHttp` (and a little more), but not in desktop, since I didn't detect any problems there. The thread pools are "daemon" which not prevent the proper shutdown in desktop or android.

2. We can improve a little the object creation in `OKHTTPClient`, but that's mostly inconsequential, since they are short lived. The main reason they provide an API to derive from an already created object (we can't use the same exact instance since we pass different settings, like user-agent, timeout, etc.) is to make sure you use the same thread pool for the `Dispatcher` and the same `ConnectionPool` for improved HTTP performance. We do that in `OKHTTPClient#newOkHttpClient` already, with the same desired effect.

3. In `Browser` if you get to the method `Browser#getPage` and inside `Browser#loadConnection`, you will see the `try-finally` block with the connection `disconnect()`.

**Comment by gubatron** [comment]
doing something like this, so next time the app restarts `HttpClientFactory#getInstance` will recreate them.

```java
// in HttpClientFactory
public static void destroyThreadPools() {
   if (okHttpClientPools == null) {
    return; //already destroyed or not created yet
   }
   okHttpClientPools.get(HttpContext.SEARCH).shutdown();
   okHttpClientPools.get(HttpContext.DOWNLOAD).shutdown();
   okHttpClientPools.get(HttpContext.MISC).shutdown();
   okHttpClientPools = null;
} 
```

**Comment by aldenml** [comment]
No, because `shutdown` only prevents new task to be submitted, not actual stop of running threads. The only way a "normal" JVM ignore a running thread is if it's daemon, which they are.

**Comment by gubatron** [comment]
what about `shutdownNow()`

**Comment by gubatron** [comment]
```
/**
     * Attempts to stop all actively executing tasks, halts the
     * processing of waiting tasks, and returns a list of the tasks
     * that were awaiting execution. These tasks are drained (removed)
     * from the task queue upon return from this method.
     *
     * <p>This method does not wait for actively executing tasks to
     * terminate.  Use {@link #awaitTermination awaitTermination} to
     * do that.
     *
     * <p>There are no guarantees beyond best-effort attempts to stop
     * processing actively executing tasks.  This implementation
     * interrupts tasks via {@link Thread#interrupt}; any task that
     * fails to respond to interrupts may never terminate.
     */
    // android-note: Removed @throws SecurityException
    public List<Runnable> shutdownNow() {
        List<Runnable> tasks;
        final ReentrantLock mainLock = this.mainLock;
        mainLock.lock();
        try {
            checkShutdownAccess();
            advanceRunState(STOP);
            interruptWorkers();
            tasks = drainQueue();
        } finally {
            mainLock.unlock();
        }
        tryTerminate();
        return tasks;
    }
```

**Comment by aldenml** [comment]
```There are no guarantees beyond best-effort attempts to stop processing actively executing tasks.```

This does nothing if the actual running thread is not prepared to be interrupted. I doubt this is actually a problem, imagine if we need to to shutdown all the running pools. It's better to design the threads to properly finish, in my opinion.

**Comment by gubatron** [comment]
gotcha, pretty hard to prepare them to do clean shutdown on InterruptedException.
I've still yet to take a snapshot of the JVM's state to see if we have a bunch of clients or not, that's really my only worry now, that the application's performance might be taking a hit with each search it makes.
