### ISSUE TITLE
[Android] Missing youtube.com search source

### ISSUE THREAD

**Issue by DeathHound6** [frostwire/frostwire#830]

**Comment by specOps2k14** [comment]
I've been running into the same issue for the past 3 months or more, it really limits the use of the app because most people that i know of use it just solely for music downloads..which is what i use it for, and every once in a while a short youtube video. But i literally have had no use for the app in the past 3+ months because of the lack of a youtube search option now, and i know that they're getting to it but it's just a huge hassle when you get used to the simple and fast way you used to be able to find music and videos

**Comment by gubatron** [comment]
yt search was removed, the project was disbanded in september and updates will be released in longer intervals now that it's only voluntary work to keep the app compatible with devices.
