### ISSUE TITLE
[android] When 3G/4G savings is on, Bittorrent is not stopping automatically when we leave WiFi network.

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#89]
The BitTorrent connectivity button is not showing the real connection status of BitTorrents on FrostWire.

This is what happen when loosing connectivity:

**NO WiFi - NO 3G/4G --> Connection status should be OFF but remains ON**

1) Go to FW Settings and check 'BitTorrent connection status is 'On' and within Torrent Settings the option **'Use 3G/4G for BitTorrent is inactive**

2) Then turn off your device WiFi connection

3) Go back to FW main menu Settings and see if the BitTorrent connection status is still "On" it should be  Off since '3G/4G for BitTorrent' is inactive and there is no WiFi.

**Comment by gubatron** [comment]
Just performed multiple tests with my phone, Android 5.x lollypop, One Plus 1. It worked absolutely perfect.

It would leave wifi and automatically pause all torrent downloads and when it came back from wifi it would start them again.

I did tests both manually disconnecting from WiFi, and also walking away from my home WiFi network  by walking 2 blocks away from my house, it worked as expected.

I'm guessing this is either a false positive, as it does take a while to go from "Downloading" to "Paused", you will see the speed dropping, and then once there's absolutely no wifi, it switches.

And it's not a false positive, then it's a fragmentation issue on which I suspect different versions of android report the network status intents differently.

**Comment by muckachina** [comment]
**Testing this on Android 6 and Android 5 pre-launch 1.7.4 (build 249):**

**NO WiFi - NO 3G/4G --> Connection status should remains OFF but I can turn it ON**

1) Go to FW Settings and check 'BitTorrent connection status is 'On' and within Torrent Settings the option **'Use 3G/4G for BitTorrent is inactive**

2) Then turn off your device WiFi connection (and I checked Mobile Data is Off)

3) Go back to FW main menu Settings and see if the BitTorrent connection status is now 'OFF', **However, I can turn it ON manually and it will remain like that...** It should say to users "Please check internet connection", otherwise FW has an inconsistency saying 'BitTorrent connection is ON', the app is not working according to the real status of the connection.

Please let me know if you want to keep this issue closed so I will close it on qa-repo too but leaving the same comment.

**Comment by muckachina** [comment]
Re-opening here on public repo...

Gubatron comment on qa ticket:
*"hmm, this is debatable. Your Bittorrent engine is effectively on, it's just that there's no internet, but everything inside remains working. I'll see what I can do. I guess it makes sense in that case because you told it to only use it on Wifi. Thanks, will try fixing."*

**Comment by gubatron** [comment]
so what do you think we should do here guys, I'm happy with both how it is and @muckachina's suggestion.

Bittorrent is working internally, it's just not connected, and once a connection is available it should continue to work as it starts to get packets.

However, I can see that this could confuse some users, "how can bittorrent be on if there's no internet?"
but addressing this I think will lead to greater complexity, you have to know somehow the following when the internet is unavailable:

Bittorrent is on, I'm going to turn it off for the user, but I will turn it back on when the internet gets back on. So this means saving yet another state somewhere in settings, and monitoring more closely connectivity status. Then once the internet is on and bittorrent is on, we should delete that setting/note from the system. Otherwise, if the user purposefully turned off Bittorrent, we're going to be turning it on for her whenever she reconnects to the internet.

Another simpler option is to still show it as "On", but have a note somewhere on the Setting screen that internet is not reachable.

CC: @marcelinkaaa @kad3mlia @alejandroarturom @aldenml

**Comment by marcelinkaaa** [comment]
So just checked it on my phone. Bittorrent connection switches to off if there is no 3G/4G or internet. The downloads pause with a connectivity message. Great. 
However - when you first install the app 'Bittorrent connection' status is off (although the app still downloads torrents just fine - which I guess is a bug too), than I manually turn it on and than go to torrent settings to make 'Use 3g/4g for Bittorrent' inactive so I only download torrents over wifi. This works but when I disable my wifi the downloads still continue. I can download our promos, as well as music as torrents. They download slow but they do download. 

I think we can leave the Bittorrent on, but with a suggested no wifi message underneath.

**Comment by gubatron** [comment]
then*

**Comment by gubatron** [comment]
👍

**Comment by kad3mlia** [comment]
agree. maybe we need to brainstorm

**Comment by kad3mlia** [comment]
Maybe we need to brainstorm a set of icon connection status - internet on/off, BitTorrent core on/off, vpn on /off ...

but let's leave that for later - it's more important to make sure FrostWire behaves in accordance to the settings, eg. it does not download from BitTorrent when BitTorrent is off after update..
