### ISSUE TITLE
[android] My audio files views photos even if does not have one

### ISSUE THREAD

**Issue by HimanshuSharma789** [frostwire/frostwire#916]
Steps to reproduce:
Go to my files -> my audio (audio tab)

It contains the files from the radio or the call recordings (which obviously does not have a photo unless its a music album).
So why it merge camera pictures with the audio files.

The given screenshot is example where the radio and call recordings can be seen but..... why it shows the photo from my gallery along with it ?????
It might be the issue with the adapter pls fix it.

<img src="https://user-images.githubusercontent.com/32963903/87221068-eb5d0f80-c386-11ea-9e8c-a89403b24cb3.png" width="360" height="680">

**Comment by gubatron** [comment]
interesting, I think this issue will manifest depending on where your phone app stores these files. We merely show the files presented to us by the Android media scanner.

If those files are not to be scanned this seems more like a privacy bug by the phone app which is not placing a marker on that folder so that it's not scanned. All they have to do is put an empty file called ".nomedia" on the folder they save those files.

I don't have that issue with my OnePlus device.

**Comment by HimanshuSharma789** [comment]
Yup u were right! Adding **.nomedia** solved the issue. 🤓
But the issue may still remain if the user him/herself created a new folder and stores the audio files in it, then they all will appear as above.
**I have a habit of storing all the songs downloaded in my MUSIC folder similarly for other audio files.** which produced this issue.

<img src="https://user-images.githubusercontent.com/32963903/87230498-1dde2b00-c3ce-11ea-8120-77e3e98ac64a.png" height="540" width="280">

- **It means this issue may reproduce if the user creates a new folder and stores audio files in it.**
whether it be call recordings or recorded radio or like a music fan like me storing songs 😂
