### ISSUE TITLE
[common] TorrentParadise.ml integration

### ISSUE THREAD

**Issue by gubatron** [frostwire/frostwire#920]
A distributed torrent index (stored on IPFS)
https://torrent-paradise.ml/

Let's do an initial integration with the website first. Ideally integration via IPFS would be a great solution to provide search results in countries that censor torrent websites.

Ideally this index exists as a database file (.sqlite) and diffs of such file that frostwire clients could fetch via IPFS, or better yet via BitTorrent.

**Comment by gubatron** [comment]
Source Code: https://github.com/urbanguacamole/torrent-paradise

**Comment by gubatron** [comment]
Search URI: `https://torrent-paradise.ml/api/search?q=<url encoded keywords>`

Sample JSON output:
```json
[
  {
    "id":"90d8bef8b5007ed7b3978dda8b536e57438fa32d",
    "text":"Martin Luther King Jr - Beyond Vietnam - A Time to Break Silence",
    "len":18651272,
    "s":0,
    "l":0
  },
  {
    "id":"7697d80cd14cc69139e9a51e466da14f5fb6f4f5",
    "text":"Martin Luther King.pdf",
    "len":26635616,
    "s":0,
    "l":0
  },
  {
    "id":"ce685482f866700a60ce4ebb2e9d3df043c137a9",
    "text":"Martin Luther King - I Have A Dream Speech August 28, 1963",
    "len":30329367,
    "s":1,
    "l":0
  },
  {
    "id":"2f9c8f4c9d295f9438f3fd58269ef0486b854a3b",
    "text":"Martin Luther King 'I have a dream'.avi",
    "len":186640384,
    "s":0,
    "l":0
  },
 ...
```

**Comment by urbanguacamole** [comment]
[torrent-paradise.ml ](https://torrent-paradise.ml)author here 

Just a nitpick: there's the centralized version (has a HTTP API) and the IPFS version (no API, slow, you would have to use a library to download the parts of the index you need and then sort the results on your machine since IPFS is all static).

I noticed that in the first post you say stored on IPFS and then give an example with the API -- these are two different services, the API can go down.

**Comment by gubatron** [comment]
Hi there @urbanguacamole glad to see you here, love your initiative. Torrent Search needs to be decentralized.

I was looking at your golang code and I see you use postgresql when you're indexing torrents from the DHT.
I didn't see any special postgresql features being used, saw pretty much 2 tables, one for telemetry, another for the torrents.
I'm wondering how to go about making your crawler configurable to so that I can use a sqlite database file instead which would be a lot more portable, also thinking how to go about creating diffs of such file that could be shared on a torrent feed.
In the end all we'd need to make this index distributed would be either having snapshots of this database synced across all nodes (simple approach), or to split that table into N shards, say 0-255 shards if the current DB is getting too big, and each shard is made up of records that point to torrents whose info hash end on a certain byte 0x00, 0x01, ..., 0xFF, and then FrostWire could use a chatty p2p protocol to ask peers in a group (peers meet over DHT keys) for torrent search results, peers send matched search results from their local copy of the shard.

**Comment by gubatron** [comment]
@urbanguacamole is there a publicly accesible pg_dump snapshot SQL file torrent of the database?

**Comment by urbanguacamole** [comment]
@gubatron I use two tables: `torrent` and `trackerdata`. One stores the seed/leech counts for each infohash for each tracker.
Then, I periodically rebuild two _materialized views_: fresh (stores the highest seed/leech count for each torrent) and search (builds upon fresh, JOINs torrent names from `torrent` and seed/leech counts from fresh and has a tsvector column (for fulltext search).

The telemetry table is so far write-only, it's there because I might implement machine learned result sorting in the future.

> split that table into N shards, say 0-255 shards if the current DB is getting too big, and each shard is made up of records that point to torrents whose info hash end on a certain byte 0x00, 0x01, ..., 0xFF, and then FrostWire could use a chatty p2p protocol to ask peers in a group (peers meet over DHT keys) for torrent search results, peers send matched search results from their local copy of the shard.

What you're describing is essentially the ipfsearch approach. Read the first paragraph [here](https://www.reddit.com/r/torrents/comments/afibhh/i_made_a_decentralized_torrent_search_site_with/edzrr8q?utm_source=share&utm_medium=web2x) to get the gist of it. Both the inverted index and the index are split up into shards. The client knows which shard to look at by first downloading the [meta file](https://ipfs.io/ipfs/Qme21itRkXCq5Comc48FMKURNwRaJguYNeNj6vmxh3fqzd/generated/inx.meta.json). For a visual explanation, open up the Network tab in Devtools on the [IPFS version](https://ipfs.io/ipfs/Qme21itRkXCq5Comc48FMKURNwRaJguYNeNj6vmxh3fqzd) and enter a common search term.

The equivalent to a chatty p2p protocol is so far IPFS -- once a node downloads a piece, it starts providing it to the rest of the network.

> is there a publicly accesible pg_dump snapshot SQL file torrent of the database?

I can make you one, what exactly are you looking for? (which tables) There's a .csv of name, infohash, seed, leech that should suffice for most users.

**Comment by urbanguacamole** [comment]
Also, don't use my spider to spider the DHT, it's stupidly slow and not good for the network and clunky. I don't use it myself anymore, I haven't deleted it yet though. Use [magnetico](https://github.com/boramalper/magnetico) (uses SQLite), or just use the magnetico community dumps.

**Comment by gubatron** [comment]
>The telemetry table is so far write-only, it's there because I might implement machine learned result sorting in the future.

Wonder what your thoughts are mixing your telemetry data, torrentdata + GPT-3
