### ISSUE TITLE
[FIXED on 6.9.2] Linux Mint 20.1 Frostwire error: libc6(>=2.32)

### ISSUE THREAD

**Issue by naddame2020** [frostwire/frostwire#952]
Trying to install Frostwire 6.9.1 build 302 on fresh install of Linux Mint 20.1 and I get an error: Dependency not satisfiable:  libc6(>=2.32). 

I am running the following for java:
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

Please also see the attached image...

![frostwire libc6](https://user-images.githubusercontent.com/78941163/107719237-98389b80-6c8c-11eb-9ff9-9bb61d7dc846.png)

**Comment by gubatron** [comment]
Hi, we just fixed this, please try our new installer, we've built it against an older linux kernel so that it doesn't look for newer libc dependencies

https://github.com/frostwire/frostwire/releases/download/frostwire-desktop-6.9.2-build-304/frostwire-6.9.2.amd64.deb

Please confirm it's working, you'd be the second user we know we've helped.

**Comment by naddame2020** [comment]
gubatron...YES...that, this works. Though it did say that it needed other installations, it did install them itself.  Thanks!!!

THIS WORKS!!!

**Comment by naddame2020** [comment]
One other thing about it...
![Miscellaneous Settings](https://user-images.githubusercontent.com/78941163/107854956-59156200-6dd4-11eb-8fea-a68cb3c0e4c7.png)

No other settings to be seen here.
